services:
  - type: web
    name: rag-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9

  - type: web
    name: rag-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_URL
        fromService:
          type: web                 
          name: mi-rag-backend      
          property: host             
      - key: REACT_APP_WS_URL
        value: "wss://mi-rag-backend.onrender.com" # ¡REEMPLAZA con tu URL real después!